public with sharing class TotvsBody {

 // public TotvsBody() {
    //  this.customerContacts = new List<CustomerContacts>();
    //  this.deliveryPlaces = new List<DeliveryPlaces>();
    // }
    
    public String shortName;
    public String customerName;
    public String personalId;
    public String email;
    public Integer entityType;
    public String address;
    public Integer customerGroup;
    public String completeAddress;
    public String neighborhood;
    public String city;
    public String state;
    public String country;
    public String zipCode;
    public String billingAddress;
    public String billingCity;
    public String billingCompleteAddress;
    public String billingCountry;
    public Integer billingIbgeCode;
    public String billingNeighborhood;
    public String billingPersonalId;
    public String billingState;
    public String billingZipCode;
    public String phone1;
    public String activityBranch;
    public Integer salesChannel;
    public Integer representativeCode;
    public Integer paymentTerms;
    public String NFeEmail;
   // public String parentName;
    public String tradeName;
    public String municipalRegistration;
    public Integer defaultHolder;
    public Integer defaultModality;
    public Integer modality;
  // public Integer additionalCredit;
  // public Integer bank;
  // public String bankBranch;
  // public Integer credit;
 // public Decimal creditLimit;
 // public Integer creditLimitCurrency;
 // public Date creditLimitDate;
 // public Date creditLimitEnd;
 // public Boolean creditSuspendedCustomer;
 // public Integer customerClassification;
 // public Integer customerBalance;
 // public String deliveryCode;
 // public String extension1;
 // public String extension2;
 // public Integer holder;
 // public String homePage;
 // public Integer ibgeCode;
 // public Boolean ICMSTaxpayer;
 // public Date implementationDate;
 // public String interstateTransactionType;
 // public Date lastSale;
 // public Integer monthsInactive;
 // public Boolean partialInvoicing;
 // public String phone2;
 // public String priceTable;
 // public String productLine;
 // public String registrationINSS;
 // public String regionCode;
 // public String shortRegion;
 // public Integer standardCarrierCode;
 // public String stateRegistration;
 // public Integer supplierGroup;
 // public String transactionType;
 // public Integer type;
 // public Date updateDate;
 // public String updateTime;
 // public String lastUpdate;
 // public Integer billingCustomer;
 // public Integer standardRevenue;
 // public List<CustomerContacts> customerContacts;
 // public List<DeliveryPlaces> deliveryPlaces;

 // public class CustomerContacts {
     // public String contactArea;
     // public String contactName;
     // public Integer customerCode;
     // public String email;
     // public String office;
     // public String phone;
     // public Integer sequence;
     // public String telefax;
  //}

 // public class DeliveryPlaces {
     // public String address;
     // public String city;
     // public String completeAddress;
     // public String deliveryCode;
     // public String mailBox;
     // public String neighborhood;
     // public String stateRegistration;
     // public String personalId;
     // public String shortName;
     // public String state;
     // public String zipCode;
     // public String country;
     // public Integer ibgeCode;
 // }
}